### ISSUE TITLE
Not able to connect to the k3s cluster from outside 

### ISSUE THREAD

**Issue by phulei** [boot2podman/boot2podman#19]
Hello 
successfully configured the k3s using podman-machine and it's k8 iso , the moment am trying to connect from the outside of the podman box , it fails and the terminal hangs and gets timed out.

tc@box:~$ kubectl get nodes
NAME   STATUS   ROLES    AGE    VERSION
box    Ready    <none>   108m   v1.13.5-k3s.1
tc@box:~$ kubectl get cluster-info
error: the server doesn't have a resource type "cluster-info"
tc@box:~$ kubectl  cluster-info
Kubernetes master is running at https://localhost:6443
CoreDNS is running at https://localhost:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
podman-machine ls
NAME   ACTIVE   DRIVER       STATE     URL                    ERRORS
box    -        virtualbox   Running   tcp://192.168.99.109

As per the guide , i have copied the k3s.yaml and copied to the config file under .kube directory and chnaged the localhost to box.

kubectl get nodes and it's gets timed out 

anything i need to do for my /etc/hosts file ?

**Comment by afbjorklund** [comment]
It (k3s) is _supposed_ to listen on the `podman-machine ip`, in your case 192.168.99.109

I'm wondering if the kubeconfig needs some editing, like if it is still pointing to 127.0.0.1 ?

https://github.com/boot2podman/boot2podman/blob/master/building_kubernetes.md#remote-access

> Copy /etc/rancher/k3s/k3s.yaml on your machine located outside the cluster as ~/.kube/config. **Then replace "localhost" with the IP or name of your k3s server.**

That should probably _should_ have said IP, since we don't do any modification of the host itself.

Like you suggest, once alternative is to add "box" to the /etc/hosts file if you want to use that.
But there is no dynamic update of it, so if you restart it with a different IP later you need to update.

There is no such script, but `$(minikube ip box)` should return the current address at least ?

----

One idea I was toying with was to have k3s/k8s support in podman-machine, like swarm in docker-machine. But I haven't released anything, so far minikube is better for handling kubernetes machines

When implemented, there would be a command to return the kubernetes configuration for a machine - somewhat similar to the current `env` command for the varlink address (i.e. like `env --swarm`).
